In [17]:
import pandas as pd
import requests
import json
import getpass

In [18]:
password = getpass.getpass()

········

Following the class example, create a function that returns the price, names of origin and arrival airports and the name of the company. Do it for all the flights between two dates that cost the same.

In [20]:
import requests

url = "https://travelpayouts-travelpayouts-flight-data-v1.p.rapidapi.com/v1/prices/calendar"

querystring = {"calendar_type":"departure_date","destination":"BCN","origin":"BER","depart_date":"2022-04-28","currency":"EUR","return_date":"2022-05-31"}

headers = {
	"X-Access-Token": str(password),
	"X-RapidAPI-Host": "travelpayouts-travelpayouts-flight-data-v1.p.rapidapi.com",
	"X-RapidAPI-Key": "248c7ee598msh82ef68e18fb9974p1bc8f9jsn1a8558b2e4ce"
}

response = requests.request("GET", url, headers=headers, params=querystring)

In [21]:
response

In [22]:
import requests

url = "https://travelpayouts-travelpayouts-flight-data-v1.p.rapidapi.com/v1/city-directions"

querystring = {"currency":"EUR","origin":"ZRH"}

headers = {
	"X-Access-Token": "78b38d15fe38d60eac333cabe89d3934",
	"X-RapidAPI-Host": "travelpayouts-travelpayouts-flight-data-v1.p.rapidapi.com",
	"X-RapidAPI-Key": "248c7ee598msh82ef68e18fb9974p1bc8f9jsn1a8558b2e4ce"
}

response = requests.request("GET", url, headers=headers, params=querystring)

In [23]:
response

In [24]:
dictionary = response.json()['data']
dates_of_flights = list(dictionary.keys())
columns = pd.json_normalize(dictionary[dates_of_flights[0]]).columns
flights = pd.DataFrame(columns=columns)
for i in range(len(dates_of_flights)):
    flights = flights.append(pd.json_normalize(dictionary[dates_of_flights[i]]))

In [27]:
flights

,origin,destination,price,airline,flight_number,departure_at,return_at,transfers,expires_at
0,ZRH,MOW,1466,EK,86,2022-04-27T22:15:00+02:00,2022-05-17T23:55:00+03:00,0,2022-04-27T11:31:25Z
0,ZRH,IST,554,LX,1072,2022-06-03T12:10:00+02:00,2022-06-06T13:55:00+03:00,0,2022-04-27T11:31:25Z
0,ZRH,AYT,508,BA,709,2022-06-19T07:10:00+02:00,2022-07-02T21:05:00+03:00,0,2022-04-27T11:31:25Z
0,ZRH,BCN,986,TP,931,2022-05-04T13:15:00+02:00,2022-05-08T06:00:00+02:00,0,2022-04-27T11:31:25Z
0,ZRH,LIS,585,TP,929,2022-05-03T06:20:00+02:00,2022-05-08T08:30:00+01:00,0,2022-04-27T11:31:25Z
0,ZRH,WAW,307,2L,1370,2022-05-08T07:05:00+02:00,2022-05-11T07:40:00+02:00,0,2022-04-27T11:31:25Z
0,ZRH,ZNZ,1733,EK,86,2022-04-27T22:15:00+02:00,2022-04-28T22:20:00+03:00,0,2022-04-27T11:31:25Z
0,ZRH,KBL,2204,LX,242,2022-04-26T13:00:00+02:00,2022-04-30T15:30:00+04:30,0,2022-04-27T11:31:25Z
0,ZRH,LON,126,U2,2048,2022-05-09T10:05:00+02:00,2022-05-16T06:45:00+01:00,0,2022-04-27T11:31:25Z
0,ZRH,MAD,220,IB,3477,2022-05-12T11:50:00+02:00,2022-05-15T22:10:00+02:00,0,2022-04-27T11:31:25Z
0,ZRH,BEG,1040,LX,1370,2022-05-19T07:10:00+02:00,2022-05-22T14:05:00+02:00,0,2022-04-27T11:31:25Z
0,ZRH,OPO,320,VY,6247,2022-05-03T09:45:00+02:00,2022-05-07T07:40:00+01:00,0,2022-04-27T11:31:25Z
0,ZRH,BKK,892,SQ,345,2022-06-09T11:45:00+02:00,2022-07-08T17:35:00+07:00,0,2022-04-27T11:31:25Z
0,ZRH,PRN,536,GM,5209,2022-04-30T16:55:00+02:00,2022-05-02T08:35:00+02:00,0,2022-04-27T11:31:25Z
0,ZRH,PMI,284,IB,5847,2022-04-29T12:50:00+02:00,2022-05-01T14:30:00+02:00,0,2022-04-27T11:31:25Z
0,ZRH,LED,1397,A3,851,2022-05-14T11:15:00+02:00,2022-05-15T19:20:00+03:00,0,2022-04-27T11:31:25Z
0,ZRH,AGP,649,IB,5639,2022-05-26T09:45:00+02:00,2022-05-29T06:35:00+02:00,0,2022-04-27T11:31:25Z
0,ZRH,BER,227,LH,1191,2022-06-10T14:40:00+02:00,2022-06-13T09:30:00+02:00,0,2022-04-27T11:31:25Z
0,ZRH,DEL,849,2L,5414,2022-07-11T12:05:00+02:00,2022-08-08T08:00:00+05:30,0,2022-04-27T11:31:25Z
0,ZRH,PAR,223,LX,638,2022-05-01T12:30:00+02:00,2022-05-02T20:35:00+02:00,0,2022-04-27T11:31:25Z
0,ZRH,AMS,298,LH,2371,2022-05-26T17:00:00+02:00,2022-05-29T07:00:00+02:00,0,2022-04-27T11:31:25Z
0,ZRH,ROM,456,2L,1740,2022-04-29T06:55:00+02:00,2022-05-02T10:05:00+02:00,0,2022-04-27T11:31:25Z
0,ZRH,SGN,1208,KL,1964,2022-04-28T19:25:00+02:00,2022-05-05T09:00:00+07:00,0,2022-04-27T11:31:25Z
0,ZRH,DXB,583,PC,950,2022-12-26T16:10:00+01:00,2023-01-21T03:05:00+04:00,0,2022-04-27T11:31:25Z
0,ZRH,CUN,1613,WK,26,2022-04-30T12:35:00+02:00,2022-05-07T23:05:00-05:00,0,2022-04-27T11:31:25Z
0,ZRH,TLV,298,A5,1415,2022-05-02T07:45:00+02:00,2022-05-10T16:30:00+03:00,0,2022-04-27T11:31:25Z
0,ZRH,TBS,466,EI,349,2022-05-15T21:45:00+02:00,2022-05-22T05:00:00+04:00,0,2022-04-27T11:31:25Z
0,ZRH,ALC,640,LX,786,2022-05-05T07:30:00+02:00,2022-05-05T17:20:00+02:00,0,2022-04-27T11:31:25Z
0,ZRH,CMB,844,EK,88,2022-04-27T15:25:00+02:00,2022-05-04T10:05:00+05:30,0,2022-04-27T11:31:25Z
0,ZRH,NYC,1436,LO,420,2022-05-06T19:50:00+02:00,2022-05-17T12:59:00-04:00,0,2022-04-27T11:31:25Z

In [28]:
def filter_1(x):
    return x[5:10] == "04-26" or x[5:10] == "04-27"

def filter_2(x):
    return x < 900

flights_26_27 = flights[flights['departure_at'].map(filter_1)]
flights_26_27 = flights_26_27[flights_26_27['price'].map(filter_2)]

In [29]:
flights_26_27[["price", "origin","destination", "airline"]]

  price origin destination airline
0   844    ZRH         CMB      EK